import {StyleSheet} from 'react-native';
import theme from './theme.styles';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.PRIMARY_COLOR,
    },
    modalContainer: {
        minHeight: 200,
        marginBottom: 25,
    },
    modalOuterContainer: {
        backgroundColor: theme.PRIMARY_COLOR,
        marginTop: 15,
    },
    reservationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        margin: 5,
        padding: 10,
        borderRadius: 8,
        borderWidth: 2,
        maxHeight: 50,
        borderColor: 'white',
        backgroundColor: 'white',
    },
    timeslotItem: {
        alignItems: 'center',
        margin: 5,
        padding: 10,
        borderRadius: 8,
        maxHeight: 50,
    },
    restaurantText: {
        fontFamily: theme.FONT_FAMILY,
        fontWeight: theme.FONT_WEIGHT_HEAVY,
        fontSize: theme.FONT_SIZE_LARGE,
        marginLeft: 15,
        color: theme.TERTIARY_COLOR,
    },
    reservationsModalText: {
        fontFamily: theme.FONT_FAMILY,
        fontWeight: theme.FONT_WEIGHT_HEAVY,
        fontSize: theme.FONT_SIZE_LARGE,
        margin: 5,
        color: theme.TERTIARY_COLOR,
    },
    reservationsModalEmptyText: {
        fontFamily: theme.FONT_FAMILY,
        fontWeight: theme.FONT_WEIGHT_MEDIUM,
        fontSize: theme.FONT_SIZE_MEDIUM,
        margin: 5,
        alignSelf: 'center',
        color: theme.TERTIARY_COLOR,
    },
    restuarantItemText: {
        color: theme.SECONDARY_COLOR,
        fontSize: theme.FONT_SIZE_MEDIUM,
        fontWeight: theme.FONT_WEIGHT_HEAVY,
    },
    restuarantItemTextDisabled: {
        color: 'gray',
        fontSize: theme.FONT_SIZE_MEDIUM,
        fontWeight: theme.FONT_WEIGHT_HEAVY,
    },
    confirmationText: {
        color: theme.TERTIARY_COLOR,
        fontSize: theme.FONT_SIZE_SMALL,
        fontFamily: theme.FONT_FAMILY,
        fontWeight: theme.FONT_WEIGHT_LIGHT,
    },
    restaurantSpacer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    placeReservationContainer: {
        margin: 10,
    },
    restaurantsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderBottomWidth: 2,
        borderBottomColor: theme.SECONDARY_COLOR,
        backgroundColor: 'white',
    },
    timeslotsContainer: {
        padding: 5,
        minHeight: 60,
        maxHeight: 60,
        backgroundColor: theme.TERTIARY_COLOR,
    },
    reservationList: {
        padding: 5,
        backgroundColor: 'white',
    },
    logo: {
        width: 50,
        height: 50,
        borderRadius: 6,
        backgroundColor: theme.TERTIARY_COLOR,
    },
    confirmReservationButton: {
        margin: 5,
        borderWidth: 2,
        borderColor: theme.TERTIARY_COLOR,
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        borderRadius: 25,
        backgroundColor: 'white',
    },
    reservationConfirmed: {
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        borderRadius: 25,
        backgroundColor: 'white',
    },
    buttonContainer: {
        borderWidth: 2,
        maxWidth: 185,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        borderRadius: 22,
        padding: 10,
        margin: 5,
        borderColor: theme.SECONDARY_COLOR,
        backgroundColor: 'white',
    },
    reservationsText: {
        fontSize: theme.FONT_SIZE_SMALL,
        fontWeight: theme.FONT_WEIGHT_MEDIUM,
        marginLeft: 10,
        fontFamily: theme.FONT_FAMILY,
    },
    rowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    deleteAction: {
        backgroundColor: 'red',
        width: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerLogo: {
        margin: 10,
        alignSelf: 'center',
    },
    headerText: {
        fontFamily: theme.FONT_FAMILY,
        fontWeight: theme.FONT_WEIGHT_HEAVY,
        fontSize: theme.FONT_SIZE_LARGE,
        marginLeft: 5,
        marginRight: 5,
    },
    rowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    buttonContainer: {
        borderWidth: 2,
        maxWidth: 185,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        borderRadius: 22,
        padding: 10,
        margin: 5,
        borderColor: theme.SECONDARY_COLOR,
        backgroundColor: 'white',
    },
    myReservationsText: {
        fontSize: theme.FONT_SIZE_SMALL,
        fontWeight: theme.FONT_WEIGHT_MEDIUM,
        marginLeft: 10,
        fontFamily: theme.FONT_FAMILY,
    },
});
